### ISSUE TITLE
help. can't log in anymore

### ISSUE THREAD

**Issue by hetkledingpunt** [impresspages/ImpressPages#826]
hi we're a clothesbank for the poor from the Netherlands without any clue of programming. A few week ago, when logging in the usual way (same password/username) to our website www.hetkledingpunt.nl via www.hetkledingpunt.nl/admin, we get the error pasted underneath. The company we got our website from advised us to go and ask at the "impress pages forum". I'm hoping that's were i'm now but don't know for sure. Can anybody help us? Your help will be greatly appreciated!!
het kleding punt

Menu 
Fatal error: Uncaught exception 'Ip\CoreException' with message 'Can't find view file '/var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/Module/Admin/View/bootstrapNav.php' (Error source: /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php line: 444 )' in /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php:327 Stack trace: #0 /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php(44): Ip\View::findView('/var/www/client...') #1 /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php(444): Ip\View::create('/var/www/client...', Array) #2 /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/Module/Admin/View/toolbar.php(17): Ip\View->generateMenu('admin_navigatio...', Array, 'bootstrapNav.ph...') #3 /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php(204): require('/var/www/client...') #4 /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/Module/Admin/System.php(95): Ip\View->render() #5 /var/www/clients/client19438 in /var/www/clients/client19438/web15685/web/ip_cms/includes/Ip/View.php on line 327

**Comment by jankus** [comment]
This error says that one of the files is missing (`bootstrapNav.php`). Ask your hosting provider what has changed just before this error started to show up. Core files cannot disappear without a reason.

**Comment by hetkledingpunt** [comment]
we didn't change or removed anything. Hosting provider keeps referring me to this forum, saying it's beyond their realm of control. 
i have no insight whatsoever in programming....

**Comment by maskas** [comment]
Your hosting company may have a backup. Try to ask if they can restore a week or month old version of the website.

**Comment by hetkledingpunt** [comment]
i'll try...they say their price is too low for such services and that i should consult this forum. there are no other options?

**Comment by mrx** [comment]
Have you contacted the person who made your website?

**Comment by maskas** [comment]
ImpressPages is an open source software. No one is paid to do the support. But from the error, that I see, I'm convinced, that some files just have disappeared from the server. That may be again because this is a very cheap hosting :)

**Comment by hetkledingpunt** [comment]
@maskas, the website indeed costs only  euro 17,- per year. 

the company says i should contact a webmaster. I asked where to find one, they said i should ask her and that there is nothing they can do for me...

@mrx i made the website, at least by logging in and dragging and droppig widgets. No programming involved or anything.

Is there anything i can do, besides hiring a webmaster, to fix this problem? is no, were can i hire one for cheap? (we're a no profit organization with much funds, just a couple of (grand)mothers wanting to help families in need)

**Comment by jankus** [comment]
@hetkledingpunt if that file is the only issue, ask your hosting to put this file in an appropriate location to restore it - https://github.com/impresspages/ImpressPages/blob/v3.9/ip_cms/includes/Ip/Module/Admin/View/bootstrapNav.php

If there are more error, please find which version of ImpressPages you are using.

P.S. did you install ImpressPages by yourself or someone helped you to do this?

**Comment by eazuka** [comment]
i may be able to help if this error still persist by tomorrow. Just say here

**Comment by timvandenhende** [comment]
@hetkledingpunt , is this fixed?
