### ISSUE TITLE
Problem when adding widget

### ISSUE THREAD

**Issue by lifeattheimprov** [impresspages/ImpressPages#851]
I was adding the table plugin when I got this error message:

Fatal error: Uncaught exception 'Ip\Exception' with message 'ipFile function accepts only paths, that start with Ip/, Plugin/, Theme/, file/. Requested path: /home/biprlamp/public_html/impresspages/Plugin/DataTableWidget/Widget/DataTable/assets/plugins' in /home/biprlamp/public_html/impresspages/Ip/Functions.php:531 Stack trace: #0 /home/biprlamp/public_html/impresspages/Ip/Internal/Content/Event.php(18): ipFile('/home/biprlamp/...') #1 /home/biprlamp/public_html/impresspages/Ip/Internal/Content/Event.php(27): Ip\Internal\Content\Event::includeResources('/home/biprlamp/...') #2 /home/biprlamp/public_html/impresspages/Ip/Internal/Content/Event.php(12): Ip\Internal\Content\Event::includeResources('Plugin/DataTabl...') #3 /home/biprlamp/public_html/impresspages/Ip/Internal/Content/Event.php(56): Ip\Internal\Content\Event::addWidgetAssets(Object(Plugin\DataTableWidget\Widget\DataTable\Controller)) #4 [internal function]: Ip\Internal\Content\Event::ipBeforeController(Array) #5 /home/biprlamp/public_html/impresspages/Ip/Interna in /home/biprlamp/public_html/impresspages/Ip/Functions.php on line 531

Here is line 531 of the file Function.php (mentioned in error message):

throw new \Ip\Exception('ipFile function accepts only paths, that start with Ip/, Plugin/, Theme/, file/. Requested path: ' . $path);

Now I can't even access the site; I just get this error message no matter what browser or computer I use.

Do I have to delete and re-install ImpressPages now?
What happened, and do I have to worry about it happening again?
I am very impressed with ImpressPages, but if this kind of error can completely lock the site up, it kind of makes the whole thing useless, doesn't it?

I was having fun learning about ImpressPages, but this is a major issue for me. I am a "techie" person, but I am looking at ImpressPages for my lesser techie friends and family; I can't have this kind of issue crashing their sites all the time.

Is there an issue with that one table plugin? Or did something else happen?

I have added a dozen or more other plugins with no issue.

Any insights into this would be greatly appreciated; as I said, I like the look, feel, and operation of ImpressPages, and I think it could be perfect for "less technical" friends and family, but if I can't find a solution to this issue, I will have to move on to something else. I can't give this to these people if I can't ensure that it will work properly.

Thanks

**Comment by lifeattheimprov** [comment]
Update...

I had a second install of ImpressPages that I was testing with, and I tried to install the same plugin. I got the same error message.

I have deleted both installs and re-installed them. Everything is fine now.

The plugin I was trying to install was the Data Table Widget by Muralt. I just wont use it; I was only testing it anyway, I had no specific need for that plugin.

Maybe it has to do with my specific server settings or php version, but it is apparently only this plugin that is an issue for me. All other plugins that I have tried, have installed without issue.

Hopefully no one else has issues like this, but in case they do, maybe something here will help them to figure their problems out.
